#  słownik z ticker'sami

tickers = {
    "ES=F": "S&P 500",
    "YM=F": "Mini Dow Jones Indus",
    "NQ=F": "Nasdaq 100",
    "RTY=F": "E-mini Russell 2000 Index Futur",
    "ZB=F": "U.S. Treasury Bond Futures",
    "ZN=F": "10-Year T-Note Futures",
    "ZF=F": "Five-Year US Treasury Note Futu",
    "ZT=F": "2-Year T-Note Futures",
    "GC=F": "Gold",
    "MGC=F": "Micro Gold Futures",
    "SI=F": "Silver",
    "PL=F": "Platinum",
    "HG=F": "Copper",
    "PA=F": "Palladium",
    "CL=F": "Crude Oil",
    "HO=F": "Heating Oil",
    "NG=F": "Natural Gas",
    "RB=F": "RBOB Gasoline",
    "BZ=F": "Brent Crude Oil",
    "B0=F": "Mont Belvieu LDH Propane",
    "ZC=F": "Corn Futures, Dec-2024",
    "ZO=F": "Oat Futures, Dec-2024",
    "KE=F": "KC HRW Wheat Futures",
    "ZR=F": "Rough Rice Futures, Sep-2024",
    "ZM=F": "S&P Composite 1500 ESG Tilted I",
    "ZL=F": "Soybean Oil Futures",
    "ZS=F": "Soybean Futures",
    "GF=F": "WisdomTree International High D",
    "HE=F": "Lean Hogs Futures",
    "LE=F": "Live Cattle Futures",
    "CC=F": "Cocoa",
    "KC=F": "Coffee",
    "CT=F": "Cotton Oct 24",
    "LBS=F": "Random Length Lumber Futures",
    "OJ=F": "Orange Juice",
    "SB=F": "Sugar"
}

