name: Pylint

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checks
    steps:
      - uses: actions/checkout@v2
      
      # Set up Python
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      # Upgrade pip and install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      
      # Install pylint
      - name: Install Pylint
        run: python -m pip install pylint==3.2.2
      
      # Run pylint on src/ directory
      - name: Run Pylint on src/
        run: pylint src/